management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

eureka:
  instance:
    health-check-url-path: /actuator/health/readiness
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

  client:
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 5