server:
  port: 8761

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}

  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    lease:
      durationInSeconds: 30
      renewalIntervalInSeconds: 10

    server:
      enableSelfPreservation: false
      responseCacheUpdateInterval: 5000


spring:
  application:
    name: discovery-server