grpc:
  server:
    port: 0

server:
  port: 0

db:
  name: ewm_stats_db

spring:
  kafka:
    consumer:
      group-id: analyzer-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"

kafka:
  topic:
    user-actions: stats.user-actions.v1
    events-similarity: stats.events-similarity.v1