server:
  port: ${PORT:8080}

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          default-filters:
            - name: Retry
              args:
                retries: 3
                statuses:
                  - SERVICE_UNAVAILABLE # 503
                  - BAD_GATEWAY         # 502
                  - GATEWAY_TIMEOUT     # 504
                methods:
                  - GET
                backoff:
                  firstBackoff: 25ms
                  maxBackoff: 300ms
                  factor: 2
                  basedOnPreviousValue: false

            - name: CircuitBreaker
              args:
                name: default-breaker
                fallbackUri: forward:/service-fallback
          routes:
            - id: comment-service-admin-route
              uri: lb://comment-service
              predicates:
                - Path=/admin/comments/**
              order: 0

            - id: comment-service-user-route
              uri: lb://comment-service
              predicates:
                - Path=/users/{userId}/comments/**
              order: 0

            - id: comment-service-event-route
              uri: lb://comment-service
              predicates:
                - Path=/events/{eventId}/comments/**
              order: 0

            - id: main-service-admin-users-route
              uri: lb://user-service
              predicates:
                - Path=/admin/users/**

            - id: main-service-admin-route
              uri: lb://main-service
              predicates:
                - Path=/admin/**

            - id: main-service-users-route
              uri: lb://main-service
              predicates:
                - Path=/users/**

            - id: main-service-categories-route
              uri: lb://main-service
              predicates:
                - Path=/categories/**

            - id: main-service-events-route
              uri: lb://main-service
              predicates:
                - Path=/events/**

            - id: main-service-compilations-route
              uri: lb://main-service
              predicates:
                - Path=/compilations/**
    loadbalancer:
      enabled: true
      retry:
        enabled: false # no retry cascades
      cache:
        enabled: true
        ttl: 30s

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s

    instances:
      default-breaker:
        baseConfig: default

  timelimiter:
    configs:
      default:
        timeoutDuration: 4s

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      probes:
        enabled: true
    gateway:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true